# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: False
google_analytics: False
title: Jie Cheng

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Jie Cheng

description: Stylish Jekyll Theme
author:
  name: Jie Cheng
  email: jie.cheng@Aliyun.com
  github: jiec827
  jianshu: users/ac456d638b07/latest_articles
  pinterest: jie_cheng/
  linkedin: in/jie-cheng-1659a8117
  bio: Stay hungry, Stay foolish
  email_md5: jie.cheng@Aliyun.com

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: assets/sky.png

BASE_PATH:

gems:
  - jekyll-paginate
